Bones = {
    [0] = { name = "SKEL_ROOT", label = "Unknown (somewhere in body)" },
    [11816] = { name = "SKEL_Pelvis", label = "Pelvis" },
    [58271] = { name = "SKEL_L_Thigh", label = "L. Upper Leg" },
    [63931] = { name = "SKEL_L_Calf", label = "L. Lower Leg" },
    [14201] = { name = "SKEL_L_Foot", label = "L. Foot" },
    [2108] = { name = "SKEL_L_Toe0", label = "L. Toe" },
    [33989] = { name = "EO_L_Foot", label = "L. Foot (EO)" },
    [26813] = { name = "EO_L_Toe", label = "L. Toe (EO)" },
    [65245] = { name = "IK_L_Foot", label = "L. Foot (IK)" },
    [57717] = { name = "PH_L_Foot", label = "L. Foot (PH)" },
    [46078] = { name = "MH_L_Knee", label = "L. Knee (MH)" },

    [51826] = { name = "SKEL_R_Thigh", label = "R. Upper Leg" },
    [36864] = { name = "SKEL_R_Calf", label = "R. Lower Leg" },
    [52301] = { name = "SKEL_R_Foot", label = "R. Foot" },
    [20781] = { name = "SKEL_R_Toe0", label = "R. Toe" },
    [4246] = { name = "EO_R_Foot", label = "R. Foot (EO)" },
    [29027] = { name = "EO_R_Toe", label = "R. Toe (EO)" },
    [35502] = { name = "IK_R_Foot", label = "R. Foot (IK)" },
    [24806] = { name = "PH_R_Foot", label = "R. Foot (PH)" },
    [16335] = { name = "MH_R_Knee", label = "R. Knee (MH)" },

    [23639] = { name = "RB_L_ThighRoll", label = "L. Upper Leg (RB)" },
    [6442] = { name = "RB_R_ThighRoll", label = "R. Upper Leg (RB)" },

    [57597] = { name = "SKEL_Spine_Root", label = "Spine Root" },
    [23553] = { name = "SKEL_Spine0", label = "Spine 0" },
    [24816] = { name = "SKEL_Spine1", label = "Spine 1" },
    [24817] = { name = "SKEL_Spine2", label = "Spine 2" },
    [24818] = { name = "SKEL_Spine3", label = "Spine 3" },

    [64729] = { name = "SKEL_L_Clavicle", label = "L. Clavicle" },
    [45509] = { name = "SKEL_L_UpperArm", label = "L. Upper Arm" },
    [61163] = { name = "SKEL_L_Forearm", label = "L. Forearm" },
    [18905] = { name = "SKEL_L_Hand", label = "L. Hand" },

    [26610] = { name = "SKEL_L_Finger00", label = "L. Finger 0" },
    [4089] = { name = "SKEL_L_Finger01", label = "L. Finger 1" },
    [4090] = { name = "SKEL_L_Finger02", label = "L. Finger 2" },
    [26611] = { name = "SKEL_L_Finger10", label = "L. Finger 10" },
    [4169] = { name = "SKEL_L_Finger11", label = "L. Finger 11" },
    [4170] = { name = "SKEL_L_Finger12", label = "L. Finger 12" },
    [26612] = { name = "SKEL_L_Finger20", label = "L. Finger 20" },
    [4185] = { name = "SKEL_L_FINGER21", label = "L. Finger 21" },
    [4186] = { name = "SKEL_L_Finger22", label = "L. Finger 22" },
    [26613] = { name = "SKEL_L_Finger30", label = "L. Finger 30" },
    [4137] = { name = "SKEL_L_Finger31", label = "L. Finger 31" },
    [4138] = { name = "SKEL_L_Finger32", label = "L. Finger 32" },
    [26614] = { name = "SKEL_L_Finger40", label = "L. Finger 40" },
    [4153] = { name = "SKEL_L_Finger41", label = "L. Finger 41" },
    [4154] = { name = "SKEL_L_Finger42", label = "L. Finger 42" },

    [60309] = { name = "PH_L_Hand", label = "L. Hand (PH)" },
    [36029] = { name = "IK_L_Hand", label = "L. Hand (IK)" },
    [61007] = { name = "RB_L_ForeArmRoll", label = "L. Forearm (RB)" },
    [5232] = { name = "RB_L_ArmRoll", label = "L. Arm (RB)" },
    [22711] = { name = "MH_L_Elbow", label = "L. Elbow (MH)" },

    [10706] = { name = "SKEL_R_Clavicle", label = "R. Clavicle" },
    [40269] = { name = "SKEL_R_UpperArm", label = "R. Upper Arm" },
    [28252] = { name = "SKEL_R_Forearm", label = "R. Forearm" },
    [57005] = { name = "SKEL_R_Hand", label = "R. Hand" },

    [39317] = { name = "SKEL_Neck_1", label = "Neck 1" },
    [24532] = { name = "SKEL_Neck_2", label = "Neck 2" },
    [31086] = { name = "SKEL_Head", label = "Head" },
    [12884] = { name = "IK_Head", label = "Head (IK)" },

    [65068] = { name = "FACIAL_facialRoot", label = "Face (Root)" },
    [25260] = { name = "FB_L_Eye_000", label = "L. Eye" },
    [27474] = { name = "FB_R_Eye_000", label = "R. Eye" },

    [2849] = { name = "FACIAL_jaw", label = "Jaw" },
    [46456] = { name = "FACIAL_chin", label = "Chin" },
    [37400] = { name = "FACIAL_forehead", label = "Forehead" },
    [16929] = { name = "FACIAL_skull", label = "Skull" },

    [64654] = { name = "SPR_L_Breast", label = "L. Chest" },
    [34911] = { name = "SPR_R_Breast", label = "R. Chest" },

    [38180] = { name = "SKEL_SADDLE", label = "Saddle" },
    [3515] = { name = "SM_M_BackSkirtRoll", label = "Back Skirt Roll" },

    [50813] = { name = "SM_CockNBalls_ROOT", label = "Genitals Root" },
    [40244] = { name = "SM_CockNBalls", label = "Genitals" },
}
